### ISSUE TITLE
6.0.0 Property 'region' does not exist on type 'typeof import

### ISSUE THREAD

**Issue by davie-robertson** [firebase/firebase-functions#1614]
### Related issues

No - checked ChangeLog too

### [REQUIRED] Version info

upgrade from ^5.1.1 to ^6.0.0

**node:**

v20.15.0

**firebase-functions:**
^6.0.0

**firebase-tools:**

13.17.0

**firebase-admin:**

### [REQUIRED] Test case

all my cloud functions were setup to run in region region("europe-west1")

I did a `firebase deploy --only functions` and saw the prompt to `npm install --save firebase-functions@latest`

I then redeployed my cloud functions and got errors in two cloud functions stating that:

` error TS2339: Property 'region' does not exist on type 'typeof import("/home/user/development/app/functions/node_modules/firebase-functions/lib/v2/index")'` 

### [REQUIRED] Steps to reproduce

```
// This function will be triggered when a user is deleted
// It will delete the user document from the database and all relationships where the user is following others
import {UserRecord} from "firebase-admin/auth";
import {getFirestore} from "firebase-admin/firestore";
import * as functions from "firebase-functions";
import * as logger from "firebase-functions/logger";

export const deleteUserDocument = functions
  .region("europe-west1")
  .auth.user()
  .onDelete(async (user: UserRecord) => {
    const db = getFirestore();
    const userRef = db.collection("users").doc(user.uid);

    try {...}
```

### [REQUIRED] Expected behavior

It should deploy in the same way as previously

### [REQUIRED] Actual behavior

error on deployment

### Were you able to successfully deploy your functions?

not since upgrading to 6.0.0

**Comment by davie-robertson** [comment]
I just went through the recent code changes to the repo and saw that the default has changed.

So updating my imports to `import * as functions from "firebase-functions/v1"; // Updated import` fixed the issue.

Has this been documented anywhere?

Are we now able to use `auth` with v2 functions?

**Comment by davie-robertson** [comment]
where is the changelog mentioned in https://github.com/firebase/firebase-functions/pull/1606 
This contains the breaking code

**Comment by sk8killer** [comment]
import functions from 'firebase-functions' 
to -->
import functions from 'firebase-functions/v1'

Did the trick for me.

**Comment by slk333** [comment]
> import functions from 'firebase-functions' to --> import functions from 'firebase-functions/v1'
> 
> Did the trick for me.

this should have been mentioned in the changelog

**Comment by tomchify** [comment]
For other who land here from search, I had a similar error when trying to deploy cloud functions:

firebase cloud functions Property 'runWith' does not exist on type 'typeof...

The import from /v1 change described above helped, but I also had to downgrade firebase-functions to 5.0 from 6.0:
`yarn add firebase-functions@^5.0.1` 
The error occurred with version ^6.0 for me.

**Comment by cabljac** [comment]
@tomchify this seems like a separate issue - I can open a new issue to track this.

**Comment by cabljac** [comment]
I will raise this with the team to see what we can do in terms of documenting this change properly

**Comment by IzaakGough** [comment]
This is now documented. The current docs explicitly show 1st gen imports as `firebase-functions/v1`, both for CommonJS and ESM, and the upgrade guide shows the v1-to-v2 import split.
- Docs checked: [Manage functions (1st gen)](https://firebase.google.com/docs/functions/1st-gen/manage-functions-1st), [2nd gen upgrade guide](https://firebase.google.com/docs/functions/2nd-gen-upgrade)
