### ISSUE TITLE
Typescript compilation error: Argument of type 'Express' is not assignable [..]

### ISSUE THREAD

**Issue by remie** [firebase/firebase-functions#587]
### Version info

**node**
v10.16.0

**firebase-functions:**
^3.3.0

**firebase-tools:**
7.8.1

**express**
^4.17.1

### Test case

```
import * as functions from 'firebase-functions';
import * as express from 'express';

const app = express();
export const api = functions.https.onRequest(app);
```

### Steps to reproduce

Add the test case in an Typescript enable environment

### Expected behavior

The `onRequest` handler should not throw Typescript compilation errors

### Actual behavior

Typescript compilation error:
```
error TS2345: Argument of type 'Express' is not assignable to parameter of type '(req: Request, resp: Response) => void'.
  Types of parameters 'req' and 'req' are incompatible.
```

### Were you able to successfully deploy your functions?

Yes, when I ignore typescript by casting it as `<any>` it deploys and runs as expected:
```
export const api = functions.https.onRequest(<any>app);
```

This is only a typing issue.

**Comment by HiddenBehindTheKeyBoard** [comment]
Vai na pasta src e faz um **npm install --save express**

**Comment by kossnocorp** [comment]
I've upgraded to `firebase-functions` from `3.3.0` to `3.6.0` and now also have this issue. I managed to fix it with any, but it's not ideal.

**Comment by jpinilloslr** [comment]
Same issue with firebase-functions 3.6.0.

**Comment by brendanmc6** [comment]
Likewise since updating to the latest version of firebase-functions. I was previously on 3.3.0.

**Comment by dcgudeman** [comment]
I am also experiencing the same issue after upgrading firebase-functions from 3.3.0 to 3.6.1

**Comment by Arno-Z** [comment]
I have fixed my firebase import to 3.3.0 in packages.json.

`   "firebase-functions": "3.3.0",`

followed by a `npm update` solved it for now. But this is confirmed an issue with the ^3.6.0 version.

**Comment by kimroen** [comment]
Still seeing this with `firebase-functions` 3.7.0. Really wanting to update for the Node 10 improvements (considering all the Google libraries rapidly dropping support for Node 8 😅)

Does anyone have any new discoveries that could point us in a direction for where to start looking to get this fixed?

**Comment by AlpSha** [comment]
Same issue with firebase-functions 3.7.0

**Comment by partriv** [comment]
i had to rollback to node 8 and my old firebase-functions and firebase-admin that was specified in package-lock. Couldn't get this working for now... will come back to it later.

**Comment by kimroen** [comment]
I just wanted to chime in here and mention that we were able to get past this now. In our case, it turned out that with the latest `firebase-admin` and `firebase-functions`, we weren't getting this error any more. However, we were getting other Express-related type errors because of a change to how parameter queries are typed, so we were just assuming the build failures were the same as before.

I would strongly suggest that you try this again and have a proper look at the error messages to make sure that you are actually still seeing this specific error.

---

📝 [Here is the error we were seeing - it's likely you'll run into this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43434#issuecomment-607181516)

**Comment by lubo08** [comment]
this export const api = functions.https.onRequest(<any>app); not work for me. Even do this still getting error. 
`node_modules/firebase-functions/lib/apps.d.ts:33:21 - error TS7033: Property 'firebaseArgs' implicitly has type 'any', because its get accessor lacks a return type annotation.

33         private get firebaseArgs();
                       ~~~~~~~~~~~~

node_modules/firebase-functions/node_modules/@types/express/index.d.ts:103:54 - error TS2315: Type 'Response' is not generic.

103     export interface Response<ResBody = any> extends core.Response<ResBody> { }`

**Comment by kimroen** [comment]
@lubo08 Could you try doing a ls-command to check which version of the express types you are running?

```
npm ls "@types/express"
```

**Comment by lubo08** [comment]
sobsoft@MacBook-Pro-uzivatela-Sobsoft functions % npm ls "@types/express"
functions@ /Users/sobsoft/workspace/sinvoicescloud/functions
├─┬ @types/cors@2.8.6
│ └── @types/express@4.17.1
└─┬ firebase-functions@3.8.0
  └── @types/express@4.17.3

**Comment by lubo08** [comment]
OK. I try several times remove node_modules folder and package-lock.json. Have no idea why but now it works. Probably I did some mistake with removing and install updated package.json .

**Comment by kimroen** [comment]
@lubo08 Great to hear! What does the ls command say now?

**Comment by lubo08** [comment]
@kimroen looks same for firebase-functions, maybe @types/cors with different version cause troubles?
@types/cors@2.8.6
│ └── @types/express@4.17.3
└─┬ firebase-functions@3.8.0
  └── @types/express@4.17.3

**Comment by kimroen** [comment]
@lubo08 Yes, I think that is likely. Thanks!

**Comment by HathTech** [comment]
Any update?

**Comment by patrickgorrell** [comment]
Any updates to this?

**Comment by Kamshak** [comment]
```
    npm i --save-dev @types/express-serve-static-core@4.17.2 @types/express@4.17.12 typescript@^4.0.2 
    npm i --save express@^4.17.1 firebase@^7.19.1 firebase-functions@^3.11.0
    npm uninstall --save-dev @types/cors
```

these work for us without errors

**Comment by NashIlli** [comment]
Hey! Any updates? Thanks a lot!

**Comment by hungtranpg** [comment]
Same issue when update `firebase-functions` from 3.3 to 3.13

**Comment by josegpulido** [comment]
Same here, just recently installed node, typescript and firebase-tools from zero. If you leave the index.ts file empty, the error still appears. Any workaround?

**Comment by josegpulido** [comment]
After some research, installing "@types/node": "^14.0.1" solve the problem for me. Be careful to install this specific version, I've tried with the latest versions but seems like doing nothing. I'm serving Express on Cloud Functions to SSR and my package.json looks like the following:
```
{
  "name": "functions",
  "scripts": {
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "14"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^9.8.0",
    "firebase-functions": "^3.14.1"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "@types/express-serve-static-core": "^4.17.24",
    "@types/node": "^14.0.1",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^4.1.5"
  },
  "private": true
}
```

> Hey! Any updates? Thanks a lot!

**Comment by taeold** [comment]
Looks like there was incompatibility with old version of the SDK with Node types. If anyone is having similar issue, please open up a new issue instead.
