### ISSUE TITLE
Typescript bug after v3.1.0

### ISSUE THREAD

**Issue by JFGHT** [firebase/firebase-functions#523]
The functions are not compiling correctly after the last release.

### [REQUIRED] Version info

**node: 10.16.0**

**firebase-functions: 3.1.0**

**firebase-tools: 7.1.0**

**Platform: Ubuntu**

**Typescript: 3.2.4**

**firebase-admin: 7.1.0**

### Steps to reproduce

`tsc --project ./ --watch`

### Expected behavior

Normal compilation of Cloud Functions.

### Actual behavior

```
node_modules/firebase-functions/lib/function-configuration.d.ts(4,64): error TS1005: ']' expected.
[1] node_modules/firebase-functions/lib/function-configuration.d.ts(4,66): error TS1134: Variable declaration expected.
[1] node_modules/firebase-functions/lib/function-configuration.d.ts(4,153): error TS1005: ';' expected.
[1] node_modules/firebase-functions/lib/function-configuration.d.ts(16,61): error TS1005: ']' expected.
[1] node_modules/firebase-functions/lib/function-configuration.d.ts(16,63): error TS1134: Variable declaration expected.
[1] node_modules/firebase-functions/lib/function-configuration.d.ts(16,93): error TS1005: ';' expected.
```

**Comment by merlinnot** [comment]
You should update your TypeScript compiler to at least v3.4.

**Comment by JFGHT** [comment]
You're right.

Thanks.

**Comment by hectorggp** [comment]
@merlinnot 
I have exactly the same problem.
I've updated all the tools to the latest versions
Could you help me find a solution?

node: 10.16.0
firebase-functions: 3.1.0
firebase-tools: 7.1.1
Platform: Windows
Typescript: 3.5.3
firebase-admin: 8.2.0

**Comment by merlinnot** [comment]
Could you please provide error logs you see?

**Comment by hectorggp** [comment]
@merlinnot I tried it is to deploy to another computer, trying to replicate the error but I could not, it just disappeared

**Comment by manel00** [comment]
Still not working after upgraading typescript.... what should i do?

**Comment by JFGHT** [comment]
Try this thread guys: https://github.com/firebase/firebase-functions/issues/404

**Comment by RaisTMJ** [comment]
> You should update your TypeScript compiler to at least v3.4.

when i update typescript to 3.4 it will produce this error 
ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.2.0 but 3.5.3 was found instead.

**Comment by malikasinger1** [comment]
this might help https://stackoverflow.com/a/59941420/4378475
