### ISSUE TITLE
error TS2315: Type 'Response' is not generic when upgrading to 3.4.0

### ISSUE THREAD

**Issue by tianhaoz95** [firebase/firebase-functions#637]
### [REQUIRED] Version info

**node:10.16.0**

**firebase-functions:3.4.0**

**firebase-tools:7.15.1**

**firebase-admin:8.10.0**

### [REQUIRED] Test case

Doesn't build with `tsc`.

### [REQUIRED] Steps to reproduce

Initialize with a hello world TypeScript example, and do `tsc`.

### [REQUIRED] Expected behavior

It should build the code in src.

### [REQUIRED] Actual behavior

```bash
##[error]node_modules/firebase-functions/lib/function-builder.d.ts(59,57): error TS2315: Type 'Response' is not generic.
```

and then error out.

Full log, see: https://github.com/tianhaoz95/iwfp/pull/376/checks?check_run_id=521083728#step:9:13

### Were you able to successfully deploy your functions?

I was able to deploy, but with upgrading to 3.4.0, probably not as it doesn't build.

**Comment by mbleigh** [comment]
As a workaround, can you try deleting your `package-lock.json` and running `npm install`? We likely need to update our type dependency slightly but that may work until we can get a patch out.

**Comment by dobromyslov** [comment]
@mbleigh Thank you for the workaround.

**Comment by jacobg** [comment]
I had to delete `node-modules` in addition to `package-lock.json` to resolve this issue.

**Comment by luckyhero613** [comment]
It works, try deleting `package-lock.json`, then run `npm install` and if after this it also not worked, try `npm install firebase angularfire2` (it will automatically download @angular/fire)

**Comment by KiranVarma-gep** [comment]
I deleted node-modules as well as package-lock.json but still throwing the same error.

**Comment by Vlad78** [comment]
I deleted node-modules as well as package-lock.json but still throwing the same error. - same issue.
Any suggestion how to fix this?
