### ISSUE TITLE
error TS2305: Module '"./common/manifest"' has no exported member 'ManifestEndpoint'

### ISSUE THREAD

**Issue by pprachit09** [firebase/firebase-functions#1031]
After updating firebase-functions to 3.17.0, I am facing an issue while deploying the changes.

_`firebase deploy --only functions`_

`node_modules/firebase-functions/lib/cloud-functions.d.ts(5,10): error TS2305: Module '"./common/manifest"' has no exported member 'ManifestEndpoint'.
node_modules/firebase-functions/lib/cloud-functions.d.ts(5,28): error TS2305: Module '"./common/manifest"' has no exported member 'ManifestRequiredAPI'.
node_modules/firebase-functions/lib/providers/https.d.ts(3,10): error TS2305: Module '"../common/manifest"' has no exported member 'ManifestEndpoint'.
node_modules/firebase-functions/lib/providers/https.d.ts(3,28): error TS2305: Module '"../common/manifest"' has no exported member 'ManifestRequiredAPI'.
`

Reverting back to 3.16.0 in package.json resolves the issue for me.

**Comment by Zelfapp** [comment]
Same issue:

```javascript
node_modules/firebase-functions/lib/cloud-functions.d.ts:5:10 - error TS2305: Module '"./common/manifest"' has no exported member 'ManifestEndpoint'.

5 import { ManifestEndpoint, ManifestRequiredAPI } from './common/manifest';
           ~~~~~~~~~~~~~~~~

node_modules/firebase-functions/lib/cloud-functions.d.ts:5:28 - error TS2305: Module '"./common/manifest"' has no exported member 'ManifestRequiredAPI'.

5 import { ManifestEndpoint, ManifestRequiredAPI } from './common/manifest';
                             ~~~~~~~~~~~~~~~~~~~

node_modules/firebase-functions/lib/providers/https.d.ts:3:10 - error TS2305: Module '"../common/manifest"' has no exported member 'ManifestEndpoint'.

3 import { ManifestEndpoint, ManifestRequiredAPI } from '../common/manifest';
           ~~~~~~~~~~~~~~~~

node_modules/firebase-functions/lib/providers/https.d.ts:3:28 - error TS2305: Module '"../common/manifest"' has no exported member 'ManifestRequiredAPI'.

3 import { ManifestEndpoint, ManifestRequiredAPI } from '../common/manifest';
```

**Comment by taeold** [comment]
Thanks for the report and sorry for the troubles.

The hotfix is underway.

**Comment by Blunderchips** [comment]
Working now for me

**Comment by IchordeDionysos** [comment]
I'm still having this error:

```
node_modules/firebase-functions/lib/v2/core.d.ts:1:10 - error TS2305: Module '"../runtime/manifest"' has no exported member 'ManifestEndpoint'.

1 import { ManifestEndpoint } from '../runtime/manifest';
           ~~~~~~~~~~~~~~~~

node_modules/firebase-functions/lib/v2/providers/https.d.ts:4:10 - error TS2305: Module '"../../runtime/manifest"' has no exported member 'ManifestEndpoint'.

4 import { ManifestEndpoint } from '../../runtime/manifest';
           ~~~~~~~~~~~~~~~~
```

**Comment by guillaumeprevost** [comment]
Thanks @taeold ! 
Updated to 3.17.1 and seems to fix it, both locally and in my CI pipeline

**Comment by creativecreatorormaybenot** [comment]
@IchordeDionysos That does look like a different error because the module in question in this issue is `common/manifest` rather than `runtime/manifest`.
